# trunk-ignore-all(checkov/CKV2_GHA_1)
name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --bin ti --release --verbose
      - name: Run tests
        run: cargo test --verbose --lib --tests --bins
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-binary
          path: target/release/ti
